[project]
name = "ai-video-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=1.5.9",
    "deep-translator>=1.11.4",
    "faster-whisper>=1.2.1",
    "ffmpeg-python>=0.2.0",
    "fpdf2>=2.8.7",
    "huggingface-hub>=1.17.0",
    "imageio-ffmpeg>=0.6.0",
    "langchain~=0.2",
    "langchain-chroma>=0.2.6",
    "langchain-community~=0.2",
    "langchain-core~=0.2",
    "langchain-huggingface>=0.3.1",
    "langchain-mistralai>=0.2.12",
    "langchain-text-splitters>=0.3.11",
    "mistralai>=2.4.8",
    "numpy>=2.4.6",
    "openai-whisper>=20250625",
    "pydantic>=2.13.4",
    "pydub>=0.25.1",
    "pypdf>=6.12.2",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.2",
    "reportlab>=4.5.1",
    "requests>=2.34.2",
    "sentence-transformers>=5.5.1",
    "spacy==3.8.7",
    "streamlit>=1.58.0",
    "streamlit-extras>=1.6.0",
    "tiktoken>=0.13.0",
    "torch>=2.12.0",
    "torchaudio>=2.11.0",
    "torchvision>=0.27.0",
    "tqdm>=4.67.3",
    "unstructured>=0.22.31",
    "watchdog>=6.0.0",
    "yt-dlp>=2026.3.17",
]
